/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telepong1;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.Timer;

/**
 *
 * @author david
 */
public class frmpong1 extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form frmpong1
     */
    int pelotax=285;
    int pelotay=225;
    int signox=1;
    int signoy=1;
    int paleta1=50;
    int paleta2=50;
    int choquepaleta;
    int lsuperior=15;
    int linferior=32;
    int marcadorp1=0;
    int marcadorp2=0;
    int rebotep1;
    int rebotep2;
            Timer temporizador = new Timer(10, new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
               pelotax+=signox*1;
               pelotay+=signoy*1;
               if(pelotay<=20 || pelotay>=370)
               {
                   signoy*=-1;

                       
                   
               }  
               if(pelotax==0)
               {
                   pelotax=285;
                   pelotay=225;
                   signox*=-1;
                   signoy*=-1;
                   marcadorp2++;
                   lblmarcador2.setText(String.valueOf(marcadorp2));

               }
               if(pelotax==570)
               {
                   pelotax=285;
                   pelotay=225;
                   signox*=-1;
                   signoy*=-1;
                   marcadorp1++;  
                   lblmarcador1.setText(String.valueOf(marcadorp1));
                   
               }
               if(pelotax==20)
               {
                   if(pelotay>=paleta1-30 )
                   {
                       rebotep1=paleta1+105;
                       if(pelotay<=rebotep1)
                       {
                           signox*=-1;
                       }
                   }
               }
               if(pelotax==550)
               {
                   if(pelotay>=paleta2-30 )
                   {
                       rebotep2=paleta2+105;
                       if(pelotay<=rebotep2)
                       {
                           signox*=-1;
                       }
                   }
               }
               
            }

            
        });
    public frmpong1() {
        initComponents();
        addKeyListener(this);
    }

    public void paint (Graphics g)
    {
        super.paint(g);
        g.setColor(Color.black);
        g.drawRect(0, paleta1, 20,75);
        g.drawRect(580,paleta2, 20,75); 
        g.drawOval(pelotax, pelotay, 30, 30);
        repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmarcador1 = new javax.swing.JLabel();
        lblmarcador2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lblmarcador1.setText("jLabel1");
        getContentPane().add(lblmarcador1);
        lblmarcador1.setBounds(120, 40, 34, 14);

        lblmarcador2.setText("jLabel2");
        getContentPane().add(lblmarcador2);
        lblmarcador2.setBounds(450, 40, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        temporizador.start();
        lblmarcador2.setText(String.valueOf(marcadorp2));
        lblmarcador1.setText(String.valueOf(marcadorp1));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpong1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblmarcador1;
    private javax.swing.JLabel lblmarcador2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {

            if(e.getKeyCode()==87)
            {               
                if(paleta1>=25)
                {
                    paleta1-=5;
                }

            }
            if(e.getKeyCode()==83)
            {
                if(paleta1<=325)
                {
                    paleta1+=5;
                }
            }            
            if(e.getKeyCode()==38)
            {
                if(paleta2>=25)
                {
                    paleta2-=5;
                }

            }
            if(e.getKeyCode()==40)
            {
                if(paleta2<=325)
                {
                    paleta2+=5;
                }

            }  


    }

    @Override
    public void keyReleased(KeyEvent ke) {
         //To change body of generated methods, choose Tools | Templates.
    }
}
